[package]
name = "optional_builder"
version = "0.1.0"
authors = ["Adilson Neto <almeidneto@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.32"
quote = "0.6.12"
proc-macro2 = "0.4.27"
